# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c407455bd7bc4fa71feee195e29e24721e44cc3c59c91582843132d4b7c8517cdb39c2617f2d427bcd3c0ce1ccf898e712d00cba9776524d9ae417aff6ff3e48

test:
  secret_key_base: 908dc9e8bef662b7f54fe024f1ba4a35176dae2a9d6ca755ff184f250edd0350b56f274442b7fae41233b76396b82b2a71e90c1e5136e4e25867007c1978e48e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
